// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj8p9Y3sfsM1jjQ0EFnU0eGHg3W5JBwQA',
    appId: '1:940394322088:web:cd6b3339eb30fd71930a9d',
    messagingSenderId: '940394322088',
    projectId: 'elitepadel-eec6b',
    authDomain: 'elitepadel-eec6b.firebaseapp.com',
    storageBucket: 'elitepadel-eec6b.firebasestorage.app',
    measurementId: 'G-J13EEZQK18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB46bm_sEGK-n9JphiIEXOM_qj1j73wZ-g',
    appId: '1:940394322088:android:61b5517d59919f18930a9d',
    messagingSenderId: '940394322088',
    projectId: 'elitepadel-eec6b',
    storageBucket: 'elitepadel-eec6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF5A7mPTpAOlrYbp9ygto467HN2jNTdJc',
    appId: '1:940394322088:ios:6fafd2f96c03c0c1930a9d',
    messagingSenderId: '940394322088',
    projectId: 'elitepadel-eec6b',
    storageBucket: 'elitepadel-eec6b.firebasestorage.app',
    iosBundleId: 'com.example.elitepadelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF5A7mPTpAOlrYbp9ygto467HN2jNTdJc',
    appId: '1:940394322088:ios:6fafd2f96c03c0c1930a9d',
    messagingSenderId: '940394322088',
    projectId: 'elitepadel-eec6b',
    storageBucket: 'elitepadel-eec6b.firebasestorage.app',
    iosBundleId: 'com.example.elitepadelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj8p9Y3sfsM1jjQ0EFnU0eGHg3W5JBwQA',
    appId: '1:940394322088:web:7a7892c6d8b1c3cb930a9d',
    messagingSenderId: '940394322088',
    projectId: 'elitepadel-eec6b',
    authDomain: 'elitepadel-eec6b.firebaseapp.com',
    storageBucket: 'elitepadel-eec6b.firebasestorage.app',
    measurementId: 'G-0W86C1M9PD',
  );
}
